#!/bin/sh
#
# Plugin to monitor imported routes from bgp and ospf protocols in bird
# use ./bird for IPv4 and ./bird6 for IPv6.
#
# nedd root rights
#
# Parameters understood:
#
#       config   (required)
#       autoconf (optional)
#
#  Made by Martin89 (martin AT martin89 DOT de)
#

#%# family=contrib
#%# capabilities=autoconf

case $(basename "$0") in
bird)
	bird='usr/sbin/birdc'
	name='bird'
	;;
bird6)
	bird='usr/sbin/birdc6'
	name='bird6'
	;;
*)
	exit 2
	;;
esac

case "$1" in
	autoconf)
		if [ -x "$bird" ]; then
			echo 'yes'
			exit 0
		else
			echo "no (can't find birdc)"
			exit 1
		fi
	;;
	config)
		echo "graph_title routes in $name"
		echo 'graph_args --base 1000 -l 0 -r'
		echo 'graph_vlabel Count'
		echo 'graph_category network'
		echo 'graph_info This graph shows the number of imported routes from a bgp or ospf protocol in bird.'
		# Attention not all protocol names valid as value name in MUNIN
		"$bird" -r show protocols | /usr/bin/awk 'FNR > 3{ if ($2 ~ /^(BGP|OSPF)$/){ print $1".label "$2" protocol "$1} }' | /usr/bin/sort -n
		exit 0
	;;
esac

"$bird" -r show protocols | /usr/bin/awk 'FNR > 3{ if ($2 ~ /^(BGP|OSPF)$/){ print $1} }' |
while reah proto; do
	"$bird" -r show protocols all "$proto" | /usr/bin/awk 'FNR == 4{ name = $1 }/^ *Routes:/{print name".value "$2; exit}'
done
