#!/bin/sh
#
# Plugin to monitor imported routes from bgp and ospf protocols in bird
#
# Parameters understood:
#
#       config   (required)
#       autoconf (optional)
#
#  Made by Martin89 (martin AT martin89 DOT de)
#

#%# family=contrib
#%# capabilities=autoconf

case "$1" in
	autoconf)
		if which birdc >/dev/null 2>&1; then
			echo 'yes'
			exit 0
		else
			echo "no (can't find birdc)"
			exit 1
		fi
	;;
	config)
		cat <<'EOM'
graph_title imported routes in bird
graph_args --base 1000 -l 0 -r
graph_vlabel Count
graph_category network
graph_info This graph shows the number of imported routes from a bgp or ospf protocol in bird.
EOM
		# Attention not all protocol names valid as value name in MUNIN
		birdc -r show protocols | awk 'FNR > 3{ if ($2 ~ /^(BGP|OSPF)$/){ print $1".label "$2" protocol "$1} }'
		exit 0
	;;
esac

for proto in $(birdc -r show protocols | awk 'FNR > 3{ if ($2 ~ /^(BGP|OSPF)$/){ print $1} }'); do
	birdc -r show protocols all "$proto" | awk '/^ *Routes:/{print $2}' | xargs -n 1 printf "$proto.value %s\n"
done
