#!/bin/sh
#
# Plugin to monitor connected network devices
#
# Parameters understood:
#
#       config   (required)
#       autoconf (optional)
#
#  Made by Martin89 (martin AT martin89 DOT de)
#

#%# family=contrib
#%# capabilities=autoconf

. $MUNIN_LIBDIR/plugins/plugin.sh

case "$1" in
	autoconf)
		if [ -x /bin/ip ]; then
			echo 'yes'
			exit 0
		else
			echo "no (can't find ip binary)"
			exit 1
		fi
	;;
	config)
		echo 'graph_title connected network devices'
		echo 'graph_args --base 1000 -l 0 -r'
		echo 'graph_vlabel Count'
		echo 'graph_category network'
		echo 'graph_info This graph shows the number of connected devices for a interface.'
		/usr/bin/awk '$1~ /^(eth|vlan|wlan|ath|ra)[0-9]+(\.[0-9]+)?/ { sub(":", ""); print $1 }' /proc/net/dev | /usr/bin/sort -n |
		while read iface; do
			iface_clean=$(clean_fieldname "$iface")
			echo "${iface_clean}.label $iface"
		done
		exit 0
	;;
esac

/usr/bin/awk '$1~ /^(eth|vlan|wlan|ath|ra)[0-9]+(\.[0-9]+)?/ { sub(":", ""); print $1 }' /proc/net/dev |
while read iface; do
	iface_clean=$(clean_fieldname $iface)
	echo -n "$iface_clean.value "
	/bin/ip neigh show dev "$iface" nud reachable | /usr/bin/cut -d ' ' -f 3 | /usr/bin/sort -u | /usr/bin/wc -l
done
