#!/bin/sh
#
# Plugin to monitor latency to the gateway
#
# Parameters understood:
#
#       config   (required)
#       autoconf (optional)
#
#  Made by Martin89 (martin AT martin89 DOT de)

#%# family=contrib
#%# capabilities=autoconf

. $MUNIN_LIBDIR/plugins/plugin.sh

getGateway4 () {
	/bin/ip -4 route show table all default | /usr/bin/awk '/^default /{print $3}' || return 1
}
getGateway6 () {
	/bin/ip -6 route show table all default | /usr/bin/awk '/^default /{print $3, $5}' || return 1
}

case "$1" in
	autoconf)
		if [ -x /bin/ip ] && [ -x /bin/ping ] && [ -x /bin/ping6 ]; then
			echo 'yes'
			exit 0
		else
			echo "no (can't find ip, ping or ping6 binary)"
			exit 1
		fi
	;;
	config)
		echo 'graph_title rtt to gateways'
		echo 'graph_args --base 1000 -l 0 -r'
		echo 'graph_vlabel latency in ms'
		echo 'graph_category network'
		echo 'graph_info This graph shows the latency to the gateway.'
		getGateway4 | while read gw; do
			gw_clear=$(clean_fieldname "$gw")
			echo "${gw_clear}.label $gw"
		done
		getGateway6 | while read gw iface; do
			gw_clear=$(clean_fieldname "${gw}_$iface")
			echo "${gw_clear}.label $gw % $iface"
		done
		exit 0
	;;
esac

{
	getGateway4 | while read gw; do
		gw_clear=$(clean_fieldname "$gw")
		/bin/ping -q -n -t 1 -c 3 "$gw" | /bin/sed 's/\// /g' | /usr/bin/awk "/^rtt/{print \"${gw_clear}.value\", \$8}"
	done
} &

{
	getGateway6 | while read gw iface; do
		gw_clear=$(clean_fieldname "${gw}_$iface")
		/bin/ping6 -q -n -t 1 -c 3 -I "$iface" "$gw" | /bin/sed 's/\// /g' | /usr/bin/awk "/^rtt/{print \"${gw_clear}.value\", \$8}"
	done
} &
wait
