#!/bin/sh
#
# Plugin to monitor latency to the gateway
#
# Parameters understood:
#
#       config   (required)
#       autoconf (optional)
#
#  Made by Martin89 (martin AT martin89 DOT de)

#%# family=contrib
#%# capabilities=autoconf

getGateway4 () {
	ip -4 route show table all default | awk '/^default /{print $3}'
}
getGateway6 () {
	ip -6 route show table all default | awk '/^default /{print $3 "_" $5}'
}

case "$1" in
	autoconf)
		if which ip >/dev/null 2>&1 && which ping >/dev/null 2>&1 && which ping6 >/dev/null 2>&1; then
			echo 'yes'
			exit 0
		else
			echo "no (can't find ip, ping or ping6 binary)"
			exit 1
		fi
	;;
	config)
		cat <<'EOM'
graph_title rtt to gateways
graph_args --base 1000 -l 0 -r
graph_vlabel latency in ms
graph_category network
graph_info This graph shows the latency to the gateway.
EOM
		for gw in $(getGateway4); do
			gw_clear=$(echo "$gw" | tr . _)
			echo "${gw_clear}.label $gw"
		done
		for gw_tuple in $(getGateway6); do
			gw_clear=$(echo "$gw_tuple" | sed 's/://g' | sed 's/%/_/')
			echo "${gw_clear}.label $gw_tuple"
		done
		exit 0
	;;
esac

{
	gw_list=$(getGateway4)
	for gw in $gw_list; do
		gw_clear=$(echo "$gw" | tr . _)
		ping -q -n -t 1 -c 3 "$gw" | sed 's/\// /g' | awk "/^rtt/{print \"${gw_clear}.value\", \$8}"
	done
} &

{
	gw_list="$(getGateway6)"
	for gw_tuple in $gw_list; do
		gw=$(echo "$gw_tuple" | cut -d _ -f 1)
		gw_clear=$(echo "$gw_tuple" | sed 's/://g' | sed 's/%/_/')
		iface=$(echo "$gw_tuple" | cut -d _ -f 2)
		ping6 -q -n -t 1 -c 3 -I "$iface" "$gw" | sed 's/\// /g' | awk "/^rtt/{print \"${gw_clear}.value\", \$8}"
	done
} &
wait
